import type { NextPage } from "next";
import Head from "next/head";
import { AuthGuard } from "../components/middlewares/authGuard";
import { HomeComponent } from "../components/pages/home/home";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthGuard>
        <main className="container">
          <HomeComponent />
        </main>
      </AuthGuard>
    </div>
  );
};

export default Home;
