import style from "./booking.module.scss";
import { Seat } from "./seat/seat";

export const Booking = () => {
  let seats = [
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "A1",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "A2",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "A3",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "A4",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "A5",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "A6",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "A7",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "A8",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "A9",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "A10",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "A11",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "A12",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "A13",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "A14",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "B1",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "B2",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "B3",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "B4",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "B5",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "B6",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "B7",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "B8",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "B9",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "B10",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "B11",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "B12",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "B13",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "B14",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "C1",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "C2",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "C3",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "C4",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "C5",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "C6",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "C7",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "C8",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "C9",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "C10",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "C11",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "C12",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "C13",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "C14",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "D1",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "D2",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "D3",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "D4",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "D5",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "D6",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "D7",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "D8",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "D9",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "D10",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "D11",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "D12",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "D13",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "D14",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "E1",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "E2",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "E3",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "E4",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "E5",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "E6",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "E7",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "E8",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "E9",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "E10",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "E11",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "E12",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "E13",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "E14",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "F1",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "F2",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "F3",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "F4",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "F5",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "F6",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "F7",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "F8",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "F9",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "F10",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "F11",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "F12",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "F13",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "F14",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "G1",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "G2",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "G3",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "G4",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "G5",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "G6",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "G7",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "G8",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "G9",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "G10",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "G11",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "G12",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "G13",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "G14",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "H1",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "H2",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "H3",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "H4",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "H5",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "H6",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "H7",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "H8",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "H9",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "H10",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "H11",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "H12",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "H13",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "H14",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "I1",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "I2",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "I3",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "I4",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "I5",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "I6",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "I7",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "I8",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "I9",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "I10",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "I11",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "I12",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "I13",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "I14",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "J1",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "J2",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "J3",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "J4",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "J5",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "J6",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "J7",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "J8",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "J9",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "J10",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "J11",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "J12",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "J13",
      user: "udisdlkfj",
    },
    {
      type: "normal",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "J14",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "K1",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "K2",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "K3",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "K4",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "K5",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "K6",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "K7",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "K8",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "K9",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "K10",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "K11",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "K12",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "K13",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "K14",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "L1",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "L2",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "L3",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "L4",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "L5",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "L6",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "L7",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "L8",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "L9",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "L10",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "L11",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "L12",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "L13",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "L14",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "M1",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "M2",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "M3",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "M4",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "M5",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "M6",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "M7",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "M8",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "M9",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "M10",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "M11",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "M12",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "M13",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "M14",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "N1",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "N2",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "N3",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "N4",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "N5",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "N6",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "N7",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "N8",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "N9",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "N10",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "N11",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "N12",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "N13",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "N14",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "O1",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "O2",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "O3",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "O4",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "O5",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "O6",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "O7",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "O8",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "O9",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "O10",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "O11",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "O12",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "O13",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "O14",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "P1",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "P2",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "P3",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "P4",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "P5",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "P6",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "P7",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "P8",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "P9",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "P10",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "P11",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "P12",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "P13",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "P14",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "Q1",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "Q2",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "Q3",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "Q4",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "Q5",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "Q6",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "Q7",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "Q8",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "Q9",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "Q10",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "Q11",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "Q12",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "Q13",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "Q14",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "R1",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "R2",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "R3",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "R4",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "R5",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "R6",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "R7",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "R8",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "R9",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "R10",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "R11",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "R12",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "R13",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "R14",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "S1",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "S2",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "S3",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "S4",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "S5",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "S6",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "S7",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "S8",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "S9",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "S10",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "S11",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "S12",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "S13",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "S14",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "T1",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "T2",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "T3",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "T4",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "T5",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "T6",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "T7",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "T8",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "T9",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "T10",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "T11",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "T12",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "T13",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "T14",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "U1",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "U2",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "U3",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "U4",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "U5",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "U6",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "U7",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "U8",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "U9",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "U10",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "U11",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "U12",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "U13",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "U14",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "V1",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "V2",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "V3",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "V4",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "V5",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "V6",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "V7",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "V8",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "V9",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "V10",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "V11",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "V12",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "V13",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "V14",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "W1",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "W2",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "W3",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "W4",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "W5",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "W6",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "W7",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "W8",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "W9",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "W10",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "W11",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "W12",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "W13",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "W14",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "X1",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "X2",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "X3",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "X4",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "X5",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "X6",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "X7",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "X8",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "X9",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "X10",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "X11",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "X12",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "X13",
      user: "udisdlkfj",
    },
    {
      type: "VIP",
      show: "show-siaof",
      theater: "theater-sadlfkjd",
      status: "open",
      bookingId: "theater-sadlfkjd-show-siaof",
      seat: "X14",
      user: "udisdlkfj",
    },
  ];
  return (
    <div className={style.booking}>
      booking
      <div className={style.theater}>
        {seats.map((el, i) => (
          <Seat 
          disabled={i%2 != 0}
          vip={el.type == "VIP"} name={el.seat} key={i} />
        ))}
      </div>
    </div>
  );
};
